# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4.1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kkdernbclp
    ports:
      - 27017:27017
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: kkdernbclp
      ME_CONFIG_MONGODB_URL: mongodb://root:kkdernbclp@mongo:27017/
    volumes:
      - mongodb:/data/db
      
  java:
    build: ./
    depends_on:
      - mongo
    ports:
      - 8080:8080
      
volumes:
  mongodb:
